apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.10.2
    helm.sh/chart: longhorn-1.10.2
  name: longhorn-default-setting
  namespace: longhorn-system
data:
  default-setting.yaml: |-
    create-default-disk-labeled-nodes: true
    default-data-path: "/var/lib/longhorn/"
    default-replica-count: "3"
    priority-class: "longhorn-critical"
    disable-revision-counter: "{\"v1\":\"true\"}"
