apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-patch
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 82.0.1
    chart: kube-prometheus-stack-82.0.1
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-admission-patch
  namespace: alertmanager
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-admission-patch
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 82.0.1
        chart: kube-prometheus-stack-82.0.1
        heritage: Helm
        release: alertmanager
      name: alertmanager-kube-promethe-admission-patch
    spec:
      containers:
        - args:
            - patch
            - --webhook-name=alertmanager-kube-promethe-admission
            - --namespace=alertmanager
            - --secret-name=alertmanager-kube-promethe-admission
            - --patch-failure-policy=
          image: ghcr.io/jkroepke/kube-webhook-certgen:1.7.7
          imagePullPolicy: IfNotPresent
          name: patch
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: alertmanager-kube-promethe-admission
  ttlSecondsAfterFinished: 60
