apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-create
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 81.5.0
    chart: kube-prometheus-stack-81.5.0
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-admission-create
  namespace: alertmanager
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-admission-create
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 81.5.0
        chart: kube-prometheus-stack-81.5.0
        heritage: Helm
        release: alertmanager
      name: alertmanager-kube-promethe-admission-create
    spec:
      containers:
        - args:
            - create
            - --host=alertmanager-kube-promethe-operator,alertmanager-kube-promethe-operator.alertmanager.svc
            - --namespace=alertmanager
            - --secret-name=alertmanager-kube-promethe-admission
          image: ghcr.io/jkroepke/kube-webhook-certgen:1.7.4
          imagePullPolicy: IfNotPresent
          name: create
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: alertmanager-kube-promethe-admission
  ttlSecondsAfterFinished: 60
