---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: alertmanager
spec:
  encryptedData:
    alertmanager.yaml: AgCObDfXKZGeEZud/HTKbw/3pnVJCIgjohO9agYGiXc6kigsYKszta3PMfWYJNT8wcLUc7nuwmsata5I+U0c5rVGeJBfM138gDd3xrZEWMSNNBSNXfId8qoWGlofgbKRGEiAjSVEAnjnKmZCXSDFC9MfxebTVhaEA5Klr1TxEJ5fU0AjtT7+MRSeYIyKV1e/RIFU0Lq3DMPV80aaQX7j7cgTShl3IYS0urlb/oMQh47Mh//N7qktkbYYdU7jBpUeBMJ85Vdj9ZAIxFVUMf3LIa0s0FftOEC799fZteEO/MrQGxj/zpJGfM3D1aXaqls2jDr67ev7PG/idIxZb9uDRfW9piDRyuTGVxItMG5S9tCI7zdkRTpi+lJQrPRV8/rOhwM9qVfu/8cQAKoZQ481jRf/B+wp2v5SLpT8MYUvQuOGkcar7YC5X7r7psHOrDO4t6bhDcVHA8o7Kf+ESlCVMKYOF9s8pU3YFaEpHaguBGQ2+qZQ2qtAupAWfTNoa8VjlybZcwxc0o1GuFhwo3IJnS8Psf4XeF3juC2UEehhXbw//b+R5yakPH0lpEKVJlDN5+9L6XI6eMzD5vazGmVqmJNt6ITjbPHn0MdrpF5uPE5keftoavTbZmekYDvrqFMReCd6yTyIpSPSPujBAcd8NoiO2ly1SxckGF1L1Og1b9YLWUgg6F1dv2vShSw/cj009ym/tM0Xj6GhW1tidnPX8XVONcs6JgwpOQlhf7YvAKACS41Mg0oY14qp7Js2kCvxbQxHsA/Wl95WhFUEgQ80pYoyc23jh3g+1wsWnxM0LwN0u7lmlNwgh0hFYGBXVRAHBaBOPU0GqROAlFtvFnZMDD6WVuSMP8KeSmU1vooEh4wnI7H6lNoE8Ldgc3V5pASMkixSUbycopzMSXNENgbuCskBB3Te/1v/6MW6ddiT0xLmDxXztNY4C7ltsJsSOlg0yXj6nv+fIwjCl5hxMixf+hOP5R1kgb96Zji5Z7IxPMjm6MRyOWPpVOo3NOjpV/qtpuZs1+yP6NcPKwYRTiBCbQl8KQUH7Si7hGQdplYjnOefJAzQTENQlditNNL94m/YW7SzRFMjcqBNleQ+60wLJ/OnvbMK6o0OmHKatmgzeR+lKC9KQIltOdSOqSEEXUG16dBMCjoz3mIKqQIqODkF0eNE2K/x8/pTUtFaozKZJMojgPiudimUAtUZC+cO1xqdE4yXrD7cCVxke2sUnHE1GBwKe1cF3OJB8C0D98CTQkro9cyDB2e+oAr9pk7qN5gifalSz4WSGR7EQaU1yjr2ss1wTx5/n16hAf+2zcOe7bYD/6xs+eflAOJSJcbgFy8wid7MX6RHcuhlCDEP3ZL1UxM4EiAWX76P123ecxe6jt8qi5PNU4xK1yPXf2ftD2qdTXvhhPk3IfmKPimU+B9RP5E5My+PrJqa30f+PW/3KYB2oQkCJgbOVUJwbXA/UE18z3Rs1DKQ/zi9sSq1GIekQ8kNuk5DpB2SxZo5GgR0QDmgNRmZqkntzJwnkJcFCwvuCFe5sKoDUpO748HYq/xrW0F0IUXFAEK3gBVvWcKVniDkb/En293CJD2s+TFVLb/6CadPkTA+tclTV6M4VqRl3bQ5K8bUVN13DxlIkl82Kg1rA40IYDNEuvjZUe40x3zL2jNLEQ48DL/EH1H/H3cVZZgAw2kOhCBnWk7T+CBMEwzc+8a2bKbeXrVkmGbMRALm3d+LoREA0+HiF9Tev2s5dsI=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 81.5.0
        chart: kube-prometheus-stack-81.5.0
        heritage: Helm
        release: alertmanager
      name: alertmanager-alertmanager-kube-promethe-alertmanager
      namespace: alertmanager
