---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: alertmanager
spec:
  encryptedData:
    alertmanager.yaml: AgBoWoBE90REIck107/hXWOsKs+d+6fir5GfeYuCTuIZ3YFWykJTB2Eg8jt5jvMJxJijImya6yoZW0WCU54iN3fbwyoWb13aNsG+5uaMJUo6xAuz9krKYInoAsGGQBeXUZxrUt8bslMR3h0BQAgqB6tCxI4sM8pgx4Nb7GIBOzSxU4L+qaB0LI8HffLrnxoQgwieOm3mTWwMpBT+K7xC72KS1sFCCY1Xn0Qh2ImoBOSE1Ofbq/4W+eLTXUtUzI9+J2M5FbqXs8ZBEmhcNLQoCtzNt4z1hHm0noRLUguYfmOHfIkVJUQomSfx0GA4nXwzdVqrheRvkke8bSFD+OJRVGxwS5576AAzx+YgNwz3PEJIL9JpiKHyFuSnB84+mrcyd16Z55luVHotybmKLoE3CwHiR2BNOUudW0PwvdUw1fm+NaIza/SJLyJMSKVtWGZqGIkTIBs0dTK+9JI6vkp9SwJhbxvztMSdsjmD1ylWlAxV0tEkrEl6dU5akHqlVHat3Qej9e97oh6E5QLyJwWNftEEBuBdztwvx2nbetpRB5T05UQUQq7UBff1EhXEQy985f/kuPsP6aGRdZ1gE/ViAHa06nsR5EtCGoli2PhB5zNEYvJWjgiqqzZXesmum75jUQBXPbSShnYNlwRh3NlRz3Bd6dBQzONr9r4tSz78kSqIF3XFSJ5PsELkDv8H49D1ijUhJY4flDJUVYiJ0kOlOhp22uk5/rpCVf/P6YEXxliN660CV4OZcbN8vOjIdG4Tob1Cqp4cN5Z4ZY/+KcLC6Lv4lpjXaH4HkCtu7Mvty5XsKVQZmyG7CZJ7JCQ98ZLjpMfw/wkcSneNoNzdfgfvWvJNphK9RI+kbZ/uRW3lkHg/b6bIgbavMH63KkgDfc65DhmARr33wT/11N3PSTuFtyPc/o6mv8FpMjDjALStU0EtVxeI4lndMOkBfhu9mUzLC80xt8Wc9dPKu+4ivXgKNV+fa/hDouhijzp7AyG14l/BgR+CkjXRExHKWb5rXJQt5UO6nGAglY9UlArGuQXj53Gy2VPhtp3rd5MYEbwPckBT6q2lSluAs+pUGRvtzx6z8wXkKcE9KNocfZXgW6MZkHMvsjRKd776IxUKL7gQmCiESi+6tLSW7t895DpWuN1KH6JZ7il/la9tV6Lfl4+cyoyFXBNbtDw8Awortaj+xTlG+zVaG/t5DBhrjFK399GYqdTwp26n38yEmLso/JPPwQ3lTHKZZZyaZwYemqvmeOgTSisr/iZsGrbLQwS9HWvorgBXnTgaeYTVpGlk++W8w+D0obhX57de+OU2vZmIRyEqI4hHCD1vRu3GezHq/jL4JjfRzvwwQr6SwS92+OVRS0zMcSdR4cmMMN2Nlsl6FKbDiUakHNPElhvRADX5t/bEplNXWmkqcoT+SyefVb15LwuImjvXzSBEz+gDoLieVO8/uEPaumF3rz2SCrQc3DaYckOR9wKFPGqUg4rtGuXbN91C3Ce13fzmb99E4uW/fa9z7YeBzaJuzDaICkGs4x1YpxgdyKnI1XC73qXIiFbg7zFS20Idiy1CJT0iJHKfeUWlFQOxdWY/Dcd1xTPxP7fePetCVT8URCKTvUUJmX/BGS5FQ2TqBdszTfZOU6JsfZc2N3aejAVY6wakkro7KfQdNNOfhCrvSa808BXGUsmShxUZeJ7CsJqnTlHWBQCzqctXefsRlZOBrQs7tfrrMrd8WKAs03XjWXQY0rcsV1pyRQE=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 81.5.0
        chart: kube-prometheus-stack-81.5.0
        heritage: Helm
        release: alertmanager
      name: alertmanager-alertmanager-kube-promethe-alertmanager
      namespace: alertmanager
