---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: alertmanager
spec:
  encryptedData:
    alertmanager.yaml: AgCmzjkpvNcKM1mSZaqkYOj3IkLPT54M7hoephZGgDZAOE3Vjrxs7uAchoaLRIgu7vlaUkznw1YkgO+MLkB7lxvvaFIxqHbRWbrftiVNF2GNELWy/GB/soe30CiSJ0vRnSDe/wL+IAqiUshgLO3ylQ+aXAFMB/ZXxywxJQ6S4M1jmySEgWdB0c5esfVPt6jGWoJbsqhfG4No0y/C4LOLVMcihueh/HLoU4XOOTTnHY2g6kfukqTKV7VhJHLcXVmNr4gBHZbzLWpv7Z5DjF1jSH7F9/KckKJJVFX7ZA9IFT6+1OIunmmagFVlM2CmZtCZYep2e/ypA6zdm6XFuuRprm6Pd2NnvAQjwKwT5oYwpggLPeuA5PKgIstX5ZUWacvXKMO0sQ/O7RwG0lcdtLZ/YsPhWYAA6pEBdDl/B1NiPDvKDxHku95bjLH2AphWKGbx9hYOMYdcyNUrK/bCIyerCDDJ7n64LbWgPZ3uCb1gS5YImotBAnvdibGcqh6P16BHK8IAJ5HAu90/wHD4uhYddYKtZk9wTrGTwXvbvvspE0R+tCoYAoyuITvG9ASlkqGxUx+2lse9svkzcb3YZ9qWA0AQZb8BJy1tWTnN3mh6tfoithzqbE9xhFw5MCeQXCaqQPKuYbz+3AVZ1ewOl8MyJINmZqh4wEA4qoEavBvhrmQGrj3Hg4QDX+uiBLysRXedZuwGh2m/nuuQboXS8U3aQfHOAifqUMizbdq8NKkOmWPecxECQ4QDdZQzSJtEILBM62vjzpD74ljAqKq6iX5//aW3HcfgG9WwbJ3UlBv7cEFUrFkfMM2zCFvpyEUOTMl016pRjcA6y75rOXUh/4NyqE1WsP/rYiYOBWHqY1C6QP+Mg2G6JHRzbuCj8dxnwhjqN+jdODUInDyu6zwtaCLu2jzZKqACbRNLEFN+zvCwwO+ts1wF1fEuOdFKLQ4GZ8jIRDsglzkMuWPI9LakLwtim1hYopMnFUtN8LOtcqdvGKHlg1VcIIYZ+LkVZw2yIpo3B9ZU9Ok25S6J0Dyg5Z9znRd192HadSY1hDZlnco1CcA8URdl+BWv1j2z9bbUm8hoNuNHrUPAr/3M4zB+lHjzWvdOxofSnmH/HYs2/s8M83c/osnzD4/vUsAsBzqWcdR02Qkhv1WLpfpyi2fJRaw8rQL6E6qxny1y/G8QcNAFXQn6zIcGYoLmeNNB/muUGB9NtM46y2aXkAp7W2F/O/QhfE01J6CBZBM6MU7gB3+5R94clduuBw98EQbLjaGVLT3gCLDwQEMLaK4N+RWXnPAEWRCz63n+6ZIu/6GxH1DoR2Kz9i5Z7nLY9R89q9wULcMCMQJkDdMQBf52op9fdpWnYdX907U2t7FSw42DsbR0MmW1uP2sZdOFuU19E4R8KZQJIpPnC36ByFoMGtlx9nWYTZ3ciT7e7XaB9MCUdiTrCDpWrnRtmbD2305Iwkmw3cOiL9ePVzc1a2yz5ZfnrUQoHJ2lGg1XJtcIjrJ1yA6GBqth23jbnabmxFTasxpusU7MAViwm0QiSzNzxC/RkOtpgxI30G7Q6q5CksBKXIpZksEWlcrQvXlP/CyiFBVYt1Sk+qD+On51uecRVWF2fWO+XY05kNP5vyOABPITWj5tHGcw4SvEN61HC1KVncMmIX2Ie9MSptdCxlJb/ln7mvgR2OuXONGSY0abUHtW6iAL2+u4k7q0EnwGs9+e3M1vQuwi1/Tfb3Cn3HwXBFzfFfnH5Jw=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 82.0.1
        chart: kube-prometheus-stack-82.0.1
        heritage: Helm
        release: alertmanager
      name: alertmanager-alertmanager-kube-promethe-alertmanager
      namespace: alertmanager
