apiVersion: v1
kind: Secret
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 81.4.3
    chart: kube-prometheus-stack-81.4.3
    heritage: Helm
    release: alertmanager
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: default
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KICBzbXRwX2Zyb206IGFsZXJ0bWFuYWdlckBleGFtcGxlLmNvbQogIHNtdHBfc21hcnRob3N0OiBsb2NhbGhvc3Q6NTg3CmluaGliaXRfcnVsZXM6Ci0gZXF1YWw6CiAgLSBuYW1lc3BhY2UKICAtIGFsZXJ0bmFtZQogIHNvdXJjZV9tYXRjaGVyczoKICAtIHNldmVyaXR5ID0gY3JpdGljYWwKICB0YXJnZXRfbWF0Y2hlcnM6CiAgLSBzZXZlcml0eSA9fiB3YXJuaW5nfGluZm8KLSBlcXVhbDoKICAtIG5hbWVzcGFjZQogIC0gYWxlcnRuYW1lCiAgc291cmNlX21hdGNoZXJzOgogIC0gc2V2ZXJpdHkgPSB3YXJuaW5nCiAgdGFyZ2V0X21hdGNoZXJzOgogIC0gc2V2ZXJpdHkgPSBpbmZvCi0gZXF1YWw6CiAgLSBuYW1lc3BhY2UKICBzb3VyY2VfbWF0Y2hlcnM6CiAgLSBhbGVydG5hbWUgPSBJbmZvSW5oaWJpdG9yCiAgdGFyZ2V0X21hdGNoZXJzOgogIC0gc2V2ZXJpdHkgPSBpbmZvCi0gdGFyZ2V0X21hdGNoZXJzOgogIC0gYWxlcnRuYW1lID0gSW5mb0luaGliaXRvcgpyZWNlaXZlcnM6Ci0gbmFtZTogd2ViLmhvb2sKcm91dGU6CiAgZ3JvdXBfYnk6CiAgLSBhbGVydG5hbWUKICBncm91cF9pbnRlcnZhbDogMTBzCiAgZ3JvdXBfd2FpdDogMTBzCiAgcmVjZWl2ZXI6IHdlYi5ob29rCiAgcmVwZWF0X2ludGVydmFsOiAxaAogIHJvdXRlczoKICAtIG1hdGNoZXJzOgogICAgLSBhbGVydG5hbWUgPSAiV2F0Y2hkb2ciCiAgICByZWNlaXZlcjogIm51bGwiCnRlbXBsYXRlczoKLSAvZXRjL2FsZXJ0bWFuYWdlci9jb25maWcvKi50bXBs
