apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 82.0.1
    chart: kube-prometheus-stack-82.0.1
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-kube-etcd
  namespace: alertmanager
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      port: http-metrics
  jobLabel: jobLabel
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: kube-prometheus-stack-kube-etcd
      release: alertmanager
