apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-etcd
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 69.2.0
    chart: kube-prometheus-stack-69.2.0
    heritage: Helm
    jobLabel: kube-etcd
    release: alertmanager
  name: alertmanager-kube-promethe-kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2381
      protocol: TCP
      targetPort: 2381
  selector:
    component: etcd
  type: ClusterIP
