apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-kube-controller-manager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.0.0
    chart: kube-prometheus-stack-65.0.0
    heritage: Helm
    jobLabel: kube-controller-manager
    release: alertmanager
  name: alertmanager-kube-promethe-kube-controller-manager
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10257
      protocol: TCP
      targetPort: 10257
  selector:
    component: kube-controller-manager
  type: ClusterIP
