apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-prometheus-stack-coredns
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 82.0.1
    chart: kube-prometheus-stack-82.0.1
    heritage: Helm
    jobLabel: coredns
    release: alertmanager
  name: alertmanager-kube-promethe-coredns
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
