apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 65.0.0
    chart: kube-prometheus-stack-65.0.0
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-alertmanager
  namespace: default
spec:
  endpoints:
    - enableHttp2: true
      path: /metrics
      port: http-web
    - path: /metrics
      port: reloader-web
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: kube-prometheus-stack-alertmanager
      release: alertmanager
      self-monitor: "true"
