apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/component: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-alertmanager
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 82.0.1
    chart: kube-prometheus-stack-82.0.1
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-alertmanager
  namespace: alertmanager
automountServiceAccountToken: true
