apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: kube-prometheus-stack-admission
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 81.4.3
    chart: kube-prometheus-stack-81.4.3
    heritage: Helm
    release: alertmanager
  name: alertmanager-kube-promethe-admission
  namespace: alertmanager
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: alertmanager-kube-promethe-operator
        namespace: default
        path: /admission-prometheusrules/validate
    failurePolicy: Ignore
    name: prometheusrulevalidate.monitoring.coreos.com
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
        resources:
          - prometheusrules
    sideEffects: None
    timeoutSeconds: 10
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: alertmanager-kube-promethe-operator
        namespace: default
        path: /admission-alertmanagerconfigs/validate
    failurePolicy: Ignore
    name: alertmanagerconfigsvalidate.monitoring.coreos.com
    rules:
      - apiGroups:
          - monitoring.coreos.com
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
        resources:
          - alertmanagerconfigs
    sideEffects: None
    timeoutSeconds: 10
