---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: default
spec:
  encryptedData:
    alertmanager.yaml: AgAOu14qhxDAGAk4SJ/wXDGxSPXD6Qmk2t918d3cTRgxV2kkXych2Y8OvDCBBXgrHv5Pg/l+SjbbQxC+YlZr4y/8856PKaUEs6bRHZ6d0eTdgSg74BWuyxRtCC2ZIGVR5A0Y2hpFEOQMUvqTmY8aZDlFg0Tr4QepgXtLm7OA7HAoHxkv44wYJyfahPcHYrBCKcqPdUjjU92UIqsFF4XM/B5cffa/8TtzUvXLcAvPFChJeoaGfRHx/H/KL2xJIA+Xq/2rkZpOVBkDlZ8dz+xydM8rI0VOeWlw4I4dIUxelDU5hYnh9k63k46ysAtpdbCGEEW6yfHUmE2+pXCfa+6qAK8xnRJPYTxQE14L6H/mLYN9OXsyxX0SCw9+/YsyTbW6HQmjxicozxgUcVK2T0mfIkiOBunVFFC8KMiP8kjpfklgwnezBOF9FVXYzM5oxy0oLK1NH0iaogHt7jg/MQudkl1IpduY80gUK9icxJzLsxiXhZ0/22qQVvoDGGTs+vrtBzdqBdgO6j4avRQHjleyI6MwqRmu8fG6554Ue2bPSbpTNgjto75mNwzqdtz0p19q7nxYiG/Q9P1BefbyQrdzVbMP6P77NCayz79aDPHO7Utf5J7alpTcmk+/Hapi8UBfLBbgUr7H89M1nEsJZFIPuic0o5CmBh4C487+BmoSBygPQ8ba8K0Zo4fBtQD5qF0KPXRA2K9OaCrDZK2DV5hlmMew4JM0bYEVlE3si87Kc9e26AKIIDb/0MmtmOMU3x2eGwMVyPISOuerfjL9afX1Hvtmuw7nyRdq3hOkHb5k1k4AYLihRYI/cU2UeGRAtQu02k/6tkMOyMFEXsE3019rADt+eg1m7IbuTA6Pfmw5R6DQAt2PRVbkjf82r0x7nOpILBn4qwScjyCZ3nhfk/TZ+AVVK28l5DD82eH1r0AUORoNHKz9ZzklwQSer9CjRC/eYO7jqOfp6Bm/bDcqu/q9wMAQ4c50PPJtE6kR4V7qgIj9q5D5QyssiHNyuGhCG0bnrrcsZ+xtlqeu5xuRAggx2gIzv2+y8cj1aRiPKnilObcdxBIf0vVKFKdi0sCgRVFRSwVQoYHNcc6mdtTTi1r7uGDrPLW8EPBNd+qtbpkv1/Vzxg1aKi8PU1Km71EaO86d23nNUI+r25rl2E3Nx+6mzxq7ZDqNrrC/BcO/mUc5O5tsjgK7Ap1FBsZiirj36E0KniO4+B6n89zYRLR4twJZ6oe94EZxGpN1paqiQ7jwPMkCSLrvGQ/nuZMY4Dkhk6KJn5VT6FoN5ZVS2BodKXyMIyf75lPJXp66hmupOokL3cBm16oxHTRvzr7MkX2HDp9O9VKB3qiqS6KCz+Gi5I6TBV2ZpGt2gh3DOFbvY7Mifx2R1jTjhFwcoSdTzyjBOyrT7Mg7HKR1fsUq5LRxo0sHJfi8CxYJzv5EJKh8ZjbXYAS/Ogp1/GiVJrAqnx1bkyF0Eiuz/11zTwCBNdkw6Pk+Ldxq5bm3aVutz+1k4YsBYFP6i3TDnRwePSgI20VsYH3rHrf6m7eCPhBE7DmaBZFZ2S/KpHL9ew9jcjZJUZjJHsYBNitFZr8OAwzLvXAEi0TCcyqFKSsrnEdYPthJ18fPwDcCGvJPDbk+8v3cf60EQO+qkdmCPHZNTnsVC3vWwWYjy6oVTV1GdOzBtc1kz1e6vWaak10F3/Npoa38HsrkMBSZKFJvHt4a66EpstLLb50OT8qB2lLc/YC+P+4cjI3a6ks=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 81.4.3
        chart: kube-prometheus-stack-81.4.3
        heritage: Helm
        release: alertmanager
      name: alertmanager-alertmanager-kube-promethe-alertmanager
      namespace: default
