---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-alertmanager-kube-promethe-alertmanager
  namespace: default
spec:
  encryptedData:
    alertmanager.yaml: AgAahowhx4ITR2t3AMH3Vix+9Qg42VlSiF0JW3EM8hvFtQoqQumJoylXmmqVH9rmFGKaR1diqMItsJSd2qFUjIWlkqkEzo1QqV5DUDsNrhm1KUmh2N4bI6LjyPZ9CFFJb5L9PnJrtEVXdB7Pa2wkuLNpqbsVHDx0YqlAeSDLAq2+sPUHQr2YJltAiboz7XdhIPgOf1htTpf1mTLLA7IynvJbo2ldlKYdj7ulj9vk+sNSgKtGJeNnfitk5pdZA7l6cVQLJ8xOLxvDmwY8q9i3RcyfSNLzZul987Efmkk3eWIyO2qUYrd1kFijhD3c+5opYQQHxIudQ5om7nipQIEyekzg5uID6WKHdWjNwJqHud5tNATb965anPRvwIwSsB1/sYYhaV8cvlH+HmFUJjUhzfEzQbCCvubYyV16m1TcJhd+bDs4qOrQ0m3Z/EhdHJRhq7jryT2kHUl447NSJ/7uvaiHAoIqwZK7rlb+1Iu52t1wvU6QjggXPodJT1DPYudhk3ZzC0HcQLnPl+fHV6pTTDt+NltbWQTY82qIh9cZHO/adnQ/lIZ3VPg/4AQF3INCVJoN7hcglXGSUOH62CmTz3ZczadH7xclLESitwT6kdkcV3tZ9aSAXaFQi3lc8iul/BJSJ/dQuDTLYUtYTH3OwIL8cBMoi4XaLOraX7eTMzcr1U7a338ZOJ7QZdgPL0TgUQFLFw5sQ5kxsFLtmnfPzC6b6jaBYjxwhQW00Qlpt8cTsAoOLrsa59p6+YXbdrePhV7m2yXsa6T61rijGCMQ1O8s0r1wcv2ynMD027P0pqG0Anvw3BmoM26OxxWpPrDZdJjaWjuY1VemMe+1ka4oI711V7ERiMt51vW/05ahNXicDeOpCW6X9Ob0mw0Hww1OZTocZSjY7MpKTFwtW2a7vZ4UHNRdwaLbyfo548hDy5QRMgQcYqSJ8m23RAP3C/nPHff7v8ASBgBirT71mM1uR75mdNEeNGWrF5OOTDy4eqlhzPLxig1oECrbGdxb+SkwMCR/S8wWNb2DC4BfYTxkMllOFBkGhmhNzznldJbueDewvRqUQ/I9ZbbGwXF4oWNFpI+jehvpthC+NNqdjc20DXrcUoevNVCA/KgW41Fip4xg0G1rDIiYskQsSAz62b0Ebk/XVzQBdgxgFPQQAByUOPqGLGpYpG/BIvAV2qa1FNcdf/CKSYAkxump2xRfYtMVkcXJw7p3NsE9zB1XyNuh9iljK8MA5eyAC/7Tnfj9E6SO5N8fEr6AyMCJLbE/Zy2kQ4/NI2lNDuYBd+EaWUUxF2HjWy8t51JtdgtW+PbJ6uXwp7N9UluQQ0HawSUEv4dasTiKVBNySxQlewlte3TbVdByWCJaNYF9l/XuvFcdsLrU/kk+ME6B5Ahk+QWj07Qee32hm5OP227NpZYwC2RqvVciNRpspdXT4+LnqwCr6HjqyDhnNU7DeyfkxI4m6eFyzd7TZYQdSCJOlllXqwDLVNYmeC9HWe6i0mOiXU1FBc9zBj1ziCOoNCPNgjjreqC6FtPR0CZg6PnoVlFpH367WGDqX+nlrZobTaXGVB9yakiTNaOiZoKCNjnLwfcVDBztQXT9iIU+W87ULBcUYSrellj6PJYB2doNAcsyTZaaVQIUXTDUouPZ6EErdHprTG6GKL0SkYEWgFD21cFmAk8l1QorA396MEUKD1S168LQ/ipec0yiL5tD2q4w9m6FhZkgh/iNgLfOggB01TMQSijgO6Q=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kube-prometheus-stack-alertmanager
        app.kubernetes.io/instance: alertmanager
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/part-of: kube-prometheus-stack
        app.kubernetes.io/version: 81.4.3
        chart: kube-prometheus-stack-81.4.3
        heritage: Helm
        release: alertmanager
      name: alertmanager-alertmanager-kube-promethe-alertmanager
      namespace: default
