apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.29
    heritage: Helm
    release: n8n
  name: n8n-public-api-configmap
  namespace: n8n
data:
  N8N_PUBLIC_API_DISABLED: "false"
  N8N_PUBLIC_API_ENDPOINT: api
  N8N_PUBLIC_API_SWAGGERUI_DISABLED: "false"
