apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.28
    heritage: Helm
    release: n8n
  name: n8n-binary-data-configmap
  namespace: n8n
data:
  N8N_DEFAULT_BINARY_DATA_MODE: default
