apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.29
    heritage: Helm
    release: n8n
  name: n8n-database-configmap
  namespace: n8n
data:
  DB_POSTGRESDB_CONNECTION_TIMEOUT: "20000"
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_HOST: n8n-postgresql
  DB_POSTGRESDB_IDLE_CONNECTION_TIMEOUT: "30000"
  DB_POSTGRESDB_POOL_SIZE: "2"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_SCHEMA: public
  DB_TYPE: postgresdb
