apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.28
    heritage: Helm
    release: n8n
  name: n8n-logging-configmap
data:
  N8N_LOG_LEVEL: info
  N8N_LOG_OUTPUT: console
