apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.29
    heritage: Helm
    release: n8n
  name: n8n-version-notifications-configmap
  namespace: n8n
data:
  N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
