apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.28
    heritage: Helm
    release: n8n
  name: n8n-metrics-configmap
  namespace: n8n
data:
  N8N_METRICS: "false"
  N8N_METRICS_INCLUDE_API_ENDPOINTS: "false"
  N8N_METRICS_INCLUDE_API_METHOD_LABEL: "false"
  N8N_METRICS_INCLUDE_API_PATH_LABEL: "false"
  N8N_METRICS_INCLUDE_API_STATUS_CODE_LABEL: "false"
  N8N_METRICS_INCLUDE_CACHE_METRICS: "false"
  N8N_METRICS_INCLUDE_CREDENTIAL_TYPE_LABEL: "false"
  N8N_METRICS_INCLUDE_DEFAULT_METRICS: "true"
  N8N_METRICS_INCLUDE_MESSAGE_EVENT_BUS_METRICS: "false"
  N8N_METRICS_INCLUDE_NODE_TYPE_LABEL: "false"
  N8N_METRICS_INCLUDE_QUEUE_METRICS: "false"
  N8N_METRICS_INCLUDE_WORKFLOW_ID_LABEL: "false"
  N8N_METRICS_PREFIX: n8n_
