apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: n8n
    chart: n8n-1.16.29
    heritage: Helm
    release: n8n
  name: n8n-workflow-history-configmap
  namespace: n8n
data:
  N8N_WORKFLOW_HISTORY_ENABLED: "true"
  N8N_WORKFLOW_HISTORY_PRUNE_TIME: "336"
