apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app.kubernetes.io/component: main
    app.kubernetes.io/instance: n8n
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: n8n
    app.kubernetes.io/part-of: n8n
    app.kubernetes.io/version: 2.6.3
    helm.sh/chart: n8n-1.16.28
  name: n8n
  namespace: n8n
spec:
  ingressClassName: nginx
  rules:
    - host: n8n.madhan.app
      http:
        paths:
          - backend:
              service:
                name: n8n
                port:
                  number: 5678
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - n8n.madhan.app
      secretName: n8n-tls
