apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app.kubernetes.io/instance: headlamp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: headlamp
    app.kubernetes.io/version: 0.40.0
    helm.sh/chart: headlamp-0.40.0
  name: headlamp
  namespace: default
spec:
  rules:
    - host: headlamp.madhan.app
      http:
        paths:
          - backend:
              service:
                name: headlamp
                port:
                  number: 80
            path: /
  tls:
    - hosts:
        - headlamp.madhan.app
      secretName: headlamp-tls
