apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-controller
  namespace: fleet
data:
  config: "{\n  \"systemDefaultRegistry\": \"\",\n  \"agentImage\": \"rancher/fleet-agent:v0.14.2\",\n  \"agentImagePullPolicy\": \"IfNotPresent\",\n  \"apiServerURL\": \"\",\n  \"apiServerCA\": \"\",\n  \"agentCheckinInterval\": \"15m\",\n  \"agentTLSMode\": \"system-store\",\n  \"agentWorkers\": {\n        \"bundledeployment\": \"50\",\n        \"drift\": \"50\"\n  },\n  \n  \"garbageCollectionInterval\": \"15m\",\n  \n  \"ignoreClusterRegistrationLabels\": false,\n  \"bootstrap\": {\n    \"paths\": \"\",\n    \"repo\": \"\",\n    \"secret\": \"\",\n    \"branch\":  \"master\",\n    \"namespace\": \"fleet-local\",\n    \"agentNamespace\": \"\"\n  },\n  \"webhookReceiverURL\": \"\",\n  \"githubURLPrefix\": \"\",\n  \"gitClientTimeout\": \"30s\"\n}\n"
