apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-controller
  namespace: fleet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-controller
  template:
    metadata:
      labels:
        app: fleet-controller
        fleet.cattle.io/shard-default: "true"
        fleet.cattle.io/shard-id: ""
    spec:
      containers:
        - command:
            - fleetcontroller
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CATTLE_ELECTION_LEASE_DURATION
              value: 30s
            - name: CATTLE_ELECTION_RETRY_PERIOD
              value: 10s
            - name: CATTLE_ELECTION_RENEW_DEADLINE
              value: 25s
            - name: BUNDLE_RECONCILER_WORKERS
              value: "50"
            - name: BUNDLEDEPLOYMENT_RECONCILER_WORKERS
              value: "50"
            - name: CLUSTER_RECONCILER_WORKERS
              value: "50"
            - name: CLUSTERGROUP_RECONCILER_WORKERS
              value: "50"
            - name: IMAGESCAN_RECONCILER_WORKERS
              value: "50"
            - name: SCHEDULE_RECONCILER_WORKERS
              value: "50"
            - name: CONTENT_RECONCILER_WORKERS
              value: "50"
          image: rancher/fleet:v0.14.2
          imagePullPolicy: IfNotPresent
          name: fleet-controller
          ports:
            - containerPort: 8080
              name: metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
        - command:
            - fleetcontroller
            - cleanup
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CATTLE_ELECTION_LEASE_DURATION
              value: 30s
            - name: CATTLE_ELECTION_RETRY_PERIOD
              value: 10s
            - name: CATTLE_ELECTION_RENEW_DEADLINE
              value: 25s
          image: rancher/fleet:v0.14.2
          imagePullPolicy: IfNotPresent
          name: fleet-cleanup
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
        - command:
            - fleetcontroller
            - agentmanagement
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FLEET_PROPAGATE_DEBUG_SETTINGS_TO_AGENTS
              value: "true"
            - name: FLEET_DEBUG_DISABLE_SECURITY_CONTEXT
              value: "false"
            - name: CATTLE_ELECTION_LEASE_DURATION
              value: 30s
            - name: CATTLE_ELECTION_RETRY_PERIOD
              value: 10s
            - name: CATTLE_ELECTION_RENEW_DEADLINE
              value: 25s
            - name: FLEET_AGENT_REPLICA_COUNT
              value: "1"
            - name: FLEET_AGENT_ELECTION_LEASE_DURATION
              value: 30s
            - name: FLEET_AGENT_ELECTION_RETRY_PERIOD
              value: 10s
            - name: FLEET_AGENT_ELECTION_RENEW_DEADLINE
              value: 25s
          image: rancher/fleet:v0.14.2
          imagePullPolicy: IfNotPresent
          name: fleet-agentmanagement
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: fleet-controller
      tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
      volumes:
        - emptyDir: {}
          name: tmp
