apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitjob
  namespace: fleet
spec:
  selector:
    matchLabels:
      app: gitjob
  template:
    metadata:
      labels:
        app: gitjob
        fleet.cattle.io/shard-default: "true"
        fleet.cattle.io/shard-id: ""
    spec:
      containers:
        - args:
            - fleetcontroller
            - gitjob
            - --gitjob-image
            - rancher/fleet:v0.11.0
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CATTLE_ELECTION_LEASE_DURATION
              value: 30s
            - name: CATTLE_ELECTION_RETRY_PERIOD
              value: 10s
            - name: CATTLE_ELECTION_RENEW_DEADLINE
              value: 25s
            - name: GITREPO_RECONCILER_WORKERS
              value: "50"
          image: rancher/fleet:v0.11.0
          name: gitjob
          ports:
            - containerPort: 8081
              name: metrics
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      serviceAccountName: gitjob
      tolerations:
        - effect: NoSchedule
          key: cattle.io/os
          operator: Equal
          value: linux
      volumes:
        - emptyDir: {}
          name: tmp
