apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.16.6
    helm.sh/chart: node-feature-discovery-0.16.6
  name: gpu-operator-node-feature-discovery-master-conf
  namespace: nvidia-gpu-operator
data:
  nfd-master.conf: |-
    extraLabelNs:
    - nvidia.com
