apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: gpu-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.18.2
    helm.sh/chart: node-feature-discovery-0.18.2
    role: master
  name: gpu-operator-node-feature-discovery-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: gpu-operator
      app.kubernetes.io/name: node-feature-discovery
      role: master
  template:
    metadata:
      annotations:
        checksum/config: c4db2edce870b152c5d443e82d15012ac2dccc7cc4a7d27935a40d01629b3f64
      labels:
        app.kubernetes.io/instance: gpu-operator
        app.kubernetes.io/name: node-feature-discovery
        role: master
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: In
                    values:
                      - ""
              weight: 1
      containers:
        - args:
            - -enable-leader-election
            - -feature-gates=NodeFeatureGroupAPI=false
            - -port=8080
          command:
            - nfd-master
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: registry.k8s.io/nfd/node-feature-discovery:v0.18.2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          name: master
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /healthz
              port: http
          resources:
            limits:
              memory: 4Gi
            requests:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /healthz
              port: http
          volumeMounts:
            - mountPath: /etc/kubernetes/node-feature-discovery
              name: nfd-master-conf
              readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: false
      hostNetwork: false
      priorityClassName: system-node-critical
      securityContext: {}
      serviceAccountName: node-feature-discovery
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Equal
          value: ""
      volumes:
        - configMap:
            items:
              - key: nfd-master.conf
                path: nfd-master.conf
            name: gpu-operator-node-feature-discovery-master-conf
          name: nfd-master-conf
