apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=false
  name: grafana-secrets
  namespace: grafana
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        projectSlug: homelab-prod
        secretsPath: /grafana
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical
  hostAPI: http://infisical-infisical-standalone-infisical.infisical.svc.cluster.local:8080
  managedSecretReference:
    creationPolicy: Owner
    secretName: grafana-admin
    secretNamespace: grafana
  resyncInterval: 60
