apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: grafana-secrets
  namespace: grafana
spec:
  authentication:
    serviceToken:
      secretsScope:
        envSlug: prod
        projectSlug: homelab-prod
        secretsPath: /grafana
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical
  hostAPI: http://infisical-infisicalstandalone-backend.infisical.svc.cluster.local:4000
  managedSecretReference:
    creationPolicy: Owner
    secretName: grafana-admin
    secretNamespace: grafana
  resyncInterval: 60
