apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: admin-secret
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 12.3.1
    helm.sh/chart: grafana-10.7.0
  name: grafana
  namespace: default
data:
  admin-password: YWRtaW4xMjM=
  admin-user: YWRtaW4=
  ldap-toml: ""
type: Opaque
