apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.2.1
    helm.sh/chart: grafana-8.5.2
  name: grafana
  namespace: default
automountServiceAccountToken: false
