apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: sealed-secrets-controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: sealed-secrets
    app.kubernetes.io/version: v0.16.0
    helm.sh/chart: sealed-secrets-1.16.0
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sealed-secrets-controller
      app.kubernetes.io/name: sealed-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: sealed-secrets-controller
        app.kubernetes.io/name: sealed-secrets
    spec:
      containers:
        - args:
            - --key-prefix
            - sealed-secrets-key
          command:
            - controller
          image: bitnami-labs/sealed-secrets-controller:0.34.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          name: sealed-secrets-controller
          ports:
            - containerPort: 8080
              name: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
          resources: {}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      securityContext:
        fsGroup: 65534
      serviceAccountName: sealed-secrets-controller
      volumes:
        - emptyDir: {}
          name: tmp
