apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.29.0
    helm.sh/chart: trivy-operator-0.31.0
  name: trivy-operator-trivy-config
  namespace: default
data:
  trivy.additionalVulnerabilityReportFields: ""
  trivy.command: image
  trivy.dbRepository: mirror.gcr.io/aquasec/trivy-db
  trivy.dbRepositoryInsecure: "false"
  trivy.filesystemScanCacheDir: /var/trivyoperator/trivy-db
  trivy.imagePullPolicy: IfNotPresent
  trivy.imageScanCacheDir: /tmp/trivy/.cache
  trivy.includeDevDeps: "false"
  trivy.javaDbRepository: mirror.gcr.io/aquasec/trivy-java-db
  trivy.mode: Standalone
  trivy.repository: mirror.gcr.io/aquasec/trivy
  trivy.resources.limits.cpu: 500m
  trivy.resources.limits.memory: 500M
  trivy.resources.requests.cpu: 100m
  trivy.resources.requests.memory: 100M
  trivy.sbomSources: ""
  trivy.severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
  trivy.skipJavaDBUpdate: "false"
  trivy.slow: "true"
  trivy.supportedConfigAuditKinds: Workload,Service,Role,ClusterRole,NetworkPolicy,Ingress,LimitRange,ResourceQuota
  trivy.tag: 0.66.0
  trivy.timeout: 5m0s
  trivy.useBuiltinRegoPolicies: "false"
  trivy.useEmbeddedRegoPolicies: "true"
