apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: trivy-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: trivy-operator
    app.kubernetes.io/version: 0.29.0
    helm.sh/chart: trivy-operator-0.31.0
  name: trivy-operator-trivy-config
  namespace: default
