apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    updatedAt: 2026-02-02 UTC 04:17:55
  labels:
    app: infisical
    chart: infisical-0.4.2
    component: backend
    heritage: Helm
    release: infisical
  name: infisical-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: infisical
      component: backend
      release: infisical
  template:
    metadata:
      annotations:
        updatedAt: 2026-02-02 UTC 04:17:55
      labels:
        app: infisical
        component: backend
        release: infisical
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: infisical-backend
          image: infisical/infisical:latest
          imagePullPolicy: IfNotPresent
          name: infisical-backend
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /api/status
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
