apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: admission-webhook
    app.kubernetes.io/instance: infisical
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/version: 1.1.0
    helm.sh/chart: ingress-nginx-4.0.13
  name: infisical-ingress-nginx-admission
  namespace: infisical
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: infisical-ingress-nginx-admission
subjects:
  - kind: ServiceAccount
    name: infisical-ingress-nginx-admission
    namespace: infisical
